
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** @author  John Miller
 *  @version 2.0
 *  @date    Sun Jul  5 00:01:42 EDT 2026
 *  @see     LICENSE (MIT style license file).
 *
 *  @note    Ordinary Differential Equation (ODE) Parameter Estimator
 *           AI Assisted Code
 */

package scalation
package dynamics

import scala.math.max

import scalation.calculus.CubicSpline
import scalation.mathstat._
import scalation.modeling.TestFit

//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `DerivativeCollocation` abstract class provides a robust foundation for fitting 
 *  arbitrary compartmental ODE models without using numerical integration solvers.
 *  @param data     a matrix containing the time steps in column 0 and observed metrics in subsequent columns.
 *  @param pBounds  a matrix containing the search space for parameters: row 0 = min, row 1 = max, row 2 = step.
 */
abstract class DerivativeCollocation (data: MatrixD, pBounds: MatrixD):

    // Extract independent time variable and dimensions
    val t: VectorD = data(?, 0)
    val timesteps: Int = t.dim

    // Cache the parameter boundary definitions
    val pMin: VectorD  = pBounds(0)
    val pMax: VectorD  = pBounds(1)
    val pStep: VectorD = pBounds(2)

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Reconstruct all missing/latent compartments algebraically using the raw 
     *  smoothed tracking data and current parameter hypotheses.
     *  @param params  the current parameter vector being evaluated.
     *  @return An array of vectors representing each structural compartment profile.
     */
    def reconstruct (params: VectorD): Array [VectorD]

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Compute the structural discrepancy (SSE) between empirical spline derivatives
     *  and the target model equations.
     *  @param params        the current parameter vector being evaluated.
     *  @param compartments  the system trajectories generated by the reconstruct method.
     *  @return The total Sum of Squared Errors (loss).
     */
    def computeLoss (params: VectorD, compartments: Array [VectorD]): Double

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Helper utility to construct a CubicSpline and safely evaluate its derivative 
     *  smoothly across the entire independent time grid.
     */
    def getDerivatives (profile: VectorD): VectorD =
        val spline = new CubicSpline (t, profile)
        VectorD (for ti <- t yield spline.derivative(ti))
    end getDerivatives

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Core execution engine. Performs a multi-start grid search over the bounded parameter
     *  space to isolate the global minimum without local optimization gradient failures.
     */
    def fit (): (VectorD, Double) =
        var bestLoss   = Double.MaxValue
        var bestParams = new VectorD (pMin.dim)

        //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
        /** Helper recursive function to evaluate an arbitrary n-dimensional hypergrid loop.
         */
        def searchSpace (index: Int, currentParams: VectorD): Unit =
            if index == pMin.dim then
                val compartments = reconstruct(currentParams)
                val currentLoss  = computeLoss(currentParams, compartments)
                if currentLoss < bestLoss then
                    bestLoss = currentLoss
                    bestParams = currentParams.copy
            else
                var v = pMin(index)
                while v <= pMax(index) do
                    currentParams(index) = v
                    searchSpace(index + 1, currentParams)
                    v += pStep(index)

        searchSpace (0, new VectorD (pMin.dim))
        (bestParams, bestLoss)
    end fit

end DerivativeCollocation


//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `SeirCollocation` class bridges the general framework with explicit SEIR dynamics.
 *  Assumes raw observed data column 1 maps to the Removed/Deaths (R) group.
 */
class SeirCollocation (data: MatrixD, pBounds: MatrixD, val N: Double) 
      extends DerivativeCollocation (data, pBounds):

    // Pre-calculate smooth R values and R derivatives from column 1
    val R_obs: VectorD = data(?, 1)
    val dR_dt: VectorD = getDerivatives(R_obs)

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Reconstruct/estimate vectors for S, E, I, R.
     *  @param params  the estimated parameters
     */
    override def reconstruct (params: VectorD): Array [VectorD] =
        val alpha = params(1)
        val gamma = params(2)
        val sigma = params(3)         // natively optimize the reporting rate parameter (e.g., 0.1 to 0.8)

        val I_est = new VectorD (timesteps)
        val E_est = new VectorD (timesteps)
        val R_est = new VectorD (timesteps)
        val S_est = new VectorD (timesteps)

       // Localized extraction to guarantee clean thread-safe compile scoping
        val localNewCases = data(?, 1)
        val localSpline   = new CubicSpline (t, localNewCases)
        val cases_smooth  = VectorD (for ti <- t yield localSpline.eval(ti))

        var accumulated_R = 0.0
        // Scaled initialization: map tracking input based on your reporting hypothesis
        I_est(0) = max (10.0, (data(0, 1) / sigma) * 4.0)
        R_est(0) = accumulated_R

        for i <- 1 until timesteps do
            val dt = t(i) - t(i-1)
            // THE STRUCTURAL SHIFT: Scale raw observations up to estimate TRUE latent infections
            val true_new_cases = cases_smooth(i-1) / sigma
            
            I_est(i) = max (0.0, I_est(i-1) + dt * (true_new_cases - (gamma * I_est(i-1))))
            accumulated_R += 0.5 * dt * (gamma * I_est(i-1) + gamma * I_est(i))
            R_est(i) = accumulated_R

        val dI_dt = getDerivatives (I_est)

        for i <- t.indices do
            E_est(i) = max (0.0, (dI_dt(i) + (gamma * I_est(i))) / alpha)
            S_est(i) = max (0.0, N - E_est(i) - I_est(i) - R_est(i))

        Array (S_est, E_est, I_est, R_obs)
    end reconstruct

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Compute the loss function (sse).
     */
    override def computeLoss (params: VectorD, compartments: Array [VectorD]): Double =
        val beta  = params(0)
        val alpha = params(1)

        val S_vec = compartments(0)
        val E_vec = compartments(1)
        val I_vec = compartments(2)

        val dE_dt = getDerivatives (E_vec)
        var sse = 0.0

        for i <- t.indices do
            val pred_dE_dt = (beta * S_vec(i) * I_vec(i) / N) - (alpha * E_vec(i))
            val error      = dE_dt(i) - pred_dE_dt
            sse += error * error
        sse / timesteps
    end computeLoss

end SeirCollocation


//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `seirCollocationTest` main function tests the `SeirCollocation` class.
 *  > runMain scalation.dynamics.seirCollocationTest
 */
@main def seirCollocationTest (): Unit =

    import modeling.forecasting.Example_Covid

    // 1. DATA PREPARATION VIA COV-19 UTILITIES

    // Request your explicit feature matrix array blocks from Example_Covid
    val features   = Array ("new_cases", "new_tests", "positive_rate")
    val dataMatrix = Example_Covid.loadData_yy(features)
    
    val timesteps = dataMatrix.dim
    val totalCols = dataMatrix.dim2

    // Build unified target input matrix (Col 0 = Time, Col 1..N = Loaded Features)
    val inputData = new MatrixD (timesteps, totalCols + 1)

    for i <- 0 until timesteps do
        inputData(i, 0) = i.toDouble                   // inject continuous time index axis into Column 0
        for j <- 0 until totalCols do
            inputData(i, j + 1) = dataMatrix(i, j)     // populate remaining feature tracks

    // 2. DEFINE TUNING GRID SEARCH MATRIX

    // Columns: [0] = Beta, [1] = Alpha, [2] = Gamma
    val bounds = MatrixD ((3, 4), 0.30,  0.10,  0.05,  0.10,   // Row 0: Min Bounds (Sigma min = 10% ascertainment)
                                  1.60,  0.50,  0.35,  0.50,   // Row 1: Max Bounds (Sigma max = 50% ascertainment)
                                  0.05,  0.05,  0.05,  0.05)   // step size

    val populationN = 330000000.0

    val t_vector     = inputData(?, 0)
    val newCases_raw = inputData(?, 1)
    val smoothEngine = new CubicSpline (t_vector, newCases_raw)
    val I_actual     = VectorD (for ti <- t_vector yield smoothEngine.eval (ti))

    // 3. EXECUTE CALIBRATION

    val model = new SeirCollocation (inputData, bounds, populationN)
    val (optimalParams, residualLoss) = model.fit ()

    // Extract smooth fitted array vectors for a localized inspection snapshot
    val finalTrajectories = model.reconstruct (optimalParams)
    val S = finalTrajectories(0)
    val E = finalTrajectories(1)
    val I = finalTrajectories(2)
    val R = finalTrajectories(3)

    val sigma = optimalParams(3)
    val I_predict = new VectorD (timesteps)
    I_predict(0) = I_actual(0) 
    
    for t_idx <- 1 until timesteps do
        val biological_infections = max (0.0, S(t_idx - 1) - S(t_idx))
        I_predict(t_idx)  = biological_infections * sigma

    println (new TestFit (I_actual.dim).testDiagnose (I_actual, I_predict))

    // 4. DISPLAY SUMMARY METRICS

    println (s"=== Modular Parameter Calibration via ScalaTion 2 ===")
    println (s"Optimal Parameters found:")
    println (s" - Beta  (Transmission Rate)        : ${optimalParams(0)}")
    println (s" - Alpha (Incubation Latency Rate)  : ${optimalParams(1)}")
    println (s" - Gamma (Recovery/Removal Velocity): ${optimalParams(2)}")
    println (s" - Sigma (Reporting Rate)           : $sigma")
    println (s"Calculated R0 Baseline Metric       : ${optimalParams(0) / optimalParams(2)}")
    println (s"Global Discrepancy Matrix MSE Loss  : $residualLoss")

    println ("\nSystem State Vectors (First 3 Timesteps):")
    for i <- 0 to 2 do
        println (s"Step $i -> S: ${S(i).toLong}, E: ${E(i).toLong}, I: ${I(i).toLong}, R: ${R(i).toLong}")

end seirCollocationTest

