
//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** @author  John Miller
 *  @version 2.0
 *  @date    Sat Aug 15 17:41:12 EDT 2026
 *  @see     LICENSE (MIT style license file).
 *
 *  @note    Gauss-Hermite Quadrature for integral approximation
 *           AI Assisted Code
 *
 *  @see https://en.wikipedia.org/wiki/Gauss-Hermite_quadrature
 */

package scalation
package random

import scala.math.abs

import scalation.mathstat.VectorD

//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `QuadratureRule` case class to hold the precomputed quadrature nodes and weights.
 *  @param nodes    the sample evaluation coordinates xi_j
 *  @param weights  the corresponding integration weights omega_j
 */
case class QuadratureRule (nodes: VectorD, weights: VectorD)


//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `GaussHermiteQuadrature` object supports a reusable Gauss-Hermite Quadrature
 *  Generator Engine that provides exact roots and weights for standard Hermite polynomials.
 */
object GaussHermiteQuadrature:

//  private val sqrt_1_5 = sqrt (1.5)
//  private val sqrt_2_5 = sqrt (2.5)

    //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
    /** Retrieves the nodes (xi) and weights (omega) for a specified number of integration points.
     *  Supports n = 3 and n = 5, which are the industry standards for filtering and DGLM estimation.
     *  @note: `sqrt_Pi` defined in `scalation.ValueType`
     *  @param n Number of integration nodes (3 or 5)
     *  @return A QuadratureRule containing the coordinate and weight vectors
     */
    def getRule (n: Int): QuadratureRule =
        n match
        case 3 =>
            // Exact roots of the 3rd-degree Hermite polynomial: H_3(x) = 8x^3 - 12x
//          val nodes   = VectorD (-sqrt_1_5, 0.0, sqrt_1_5)
//          val weights = VectorD (sqrt_Pi / 6.0, (2.0 * sqrt_Pi) / 3.0, sqrt_Pi / 6.0 )
            val nodes   = VectorD(-1.2247448713915890, 0.0, 1.2247448713915890)
            val weights = VectorD(0.2954089751509193, 1.1816359006036772, 0.2954089751509193)
               
            QuadratureRule(nodes, weights)

        case 5 =>
            // Exact roots and Christoffel weights of the 5th-degree Hermite polynomial: H_5(x) = 32x^5 - 160x^3 + 120x
            val nodes = VectorD (-2.0201828704560856,
                                 -0.9585724646138185,
                                  0.0,
                                  0.9585724646138185,
                                  2.0201828704560856)
            val weights = VectorD (0.0199532420590459,
                                   0.3936193231522412,
                                   0.9453087204829419,
                                   0.3936193231522412,
                                   0.0199532420590459)
            QuadratureRule (nodes, weights)

        case _ =>
            throw new IllegalArgumentException ("Only 3-node and 5-node configurations are hardcoded for high performance")
    end getRule

end GaussHermiteQuadrature


//:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
/** The `gaussHermiteQuadratuteTest` test the gaussHermiteQuadratuteTest class.
 *  > runMain scalation.random.gaussHermiteQuadratuteTest
 */
@main def gaussHermiteQuadratuteTest (): Unit =

    banner ("--- Verification Matrix for Gauss-Hermite Quadrature ---")

    // Mathematical Ground Truth for verifying the algorithm:
    // The definite integral of f(x) = x^2 against the weight e^(-x^2) from -inf to +inf 
    // evaluates analytically to exactly: sqrt(pi) / 2
    val exactGroundTruth = sqrt_Pi / 2.0
    println (s"Analytical Ground Truth Target Score: $exactGroundTruth\n")

    // Define the integration problem arrays for testing
    val testingNodes = Array (3, 5)

    for n <- testingNodes do
        println (s"--- Evaluating $n-Node Quadrature Configuration ---")
        
        // Retrieve the precomputed static rules from your generic utility
        val rule = GaussHermiteQuadrature.getRule (n)
        
        // Print the structural coordinate maps generated by the tool
        println ("Generated Quadrature Mapping Layout:")
        for j <- 0 until rule.nodes.length do
            println (s"  Node Index $j | Coordinate Node (xi): ${"%10.6f".format(rule.nodes(j))} | Weight (omega): ${"%10.6f".format(rule.weights(j))}")
        
        // Evaluate the integration test function: f(x) = x^2
        // Gauss-Hermite quadrature says: Integral of f(x)e^(-x^2) dx ≈ sum(omega_j * f(xi_j))
        val numericalApproximation = (0 until rule.nodes.length).map { j =>
            val xi    = rule.nodes(j)
            val omega = rule.weights(j)
            
            val fx = xi * xi                                     // test Function: f(x) = x^2
            omega * fx
        }.sum

        val absoluteError = abs (numericalApproximation - exactGroundTruth)
        
        println (s"Numerical Approximation Result : $numericalApproximation")
        println (s"Computed Absolute Error Residual: ${"%10.2e".format(absoluteError)}")
        
        // Structural validation assert check: 
        // A 3-node or 5-node rule integrates a quadratic polynomial with near-perfect precision
        if (absoluteError < 1e-12) then
            println(s"-> SUCCESS: $n-Node calculation matched ground truth with zero machine leakage.")
        else
            println(s"-> WARNING: Local drift observed.")
        println ("-" * 80)
    end for

    banner ("--- Verified: Context Carrier Compliant for Probit, Poisson, and Beta  ---")

end gaussHermiteQuadratuteTest

